<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use App\Entity\FormInscription;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class newFormInscription extends AbstractType
{
public function buildForm(FormBuilderInterface $builder, array $options)
{
    //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub



        $builder
            ->add('prenom', TextType::class)
            ->add('nom', TextType::class)
            ->add('dateNaissance', TextType::class)
            ->add('lieuNaissance', TextType::class)
            ->add('adresse', TextType::class)
            ->add('complementAdresse', TextType::class, ['required' => false])
            ->add('numTel', TextType::class)
            ->add('email', EmailType::class)
            ->add('anneeCours', ChoiceType::class, [
                'choices' => [
                    'Bachelor 1' => 'Bachelor 1',
                    'Bachelor 2' => 'Bachelor 2',
                    'Bachelor 3' => 'Bachelor 3',
                    'Prepa' => 'Prepa',
                ],
            ]);
    }
    public function configureOptions(OptionsResolver $resolver)

    {
    $resolver->setDefaults([
        'data_class' => null,
    ]);

    }

}